# src/main/resources/application.yml
spring:
  application:
    name: aaa-service

  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/aaa}
    username: ${DB_USERNAME:aaa_user}
    password: ${DB_PASSWORD:change-me}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate           # Schema managed by Flyway
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}
  observations:
    key-values:
      env: ${APP_ENV:default}

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG    # Turn to INFO in prod
    com.yourorg.aaa: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%X{traceId:-}-[%X{spanId:-}]] %logger{36} - %msg%n"

# Swagger UI at /swagger-ui.html
springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    path: /swagger-ui.html

# JWT & security (used by SecurityConfig / TokenService)
security:
  jwt:
    issuer: ${JWT_ISSUER:aaa-service}
    secret: ${JWT_SECRET:please-change-in-prod}
    access-token:
      ttl: ${JWT_ACCESS_TTL:PT15M}      # ISO-8601 duration
    refresh-token:
      ttl: ${JWT_REFRESH_TTL:P7D}

# CORS defaults (can be tightened per env)
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

aaa:
  seed:
    enabled: true
    admin:
      username: admin
      email: admin@example.com
      password: P@ssw0rd!
    client:
      enabled: true
      id: svc_bootstrap
      name: Bootstrap Client